services:
  - type: web
    name: telegram-bot
    runtime: python
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    env: python